name:                exalog-engine
version:             0.1.0.0
github:              "madgen/exalog-engine"
license:             BSD-3-Clause
author:              "Mistral Contrastin"
maintainer:          "madgenhetic@gmail.com"
copyright:           "2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A Datalog engine with support for external processes as predicates
category:            Language
description:         Please see the README on GitHub at <https://github.com/madgen/exalog-engine#readme>

default-extensions:
- NoImplicitPrelude
- LambdaCase
- OverloadedStrings

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates

dependencies:
- base >= 4.7 && < 5
- bimap >= 0.4 && < 0.5
- bytestring >= 0.10 && < 0.11
- containers >= 0.6 && < 0.7
- comonad >= 5.0 && < 5.1
- fgl >= 5.7 && < 5.8
- finite-typelits >= 0.1.4 && < 0.1.5
- singletons >= 2.5 && < 2.6
- transformers >= 0.5 && < 0.6
- protolude >= 0.2 && < 0.3
- text >= 1.2 && < 1.3
- vector-sized >= 1.2 && < 1.3
- ghc-typelits-natnormalise >= 0.7 && < 0.8
- pretty >= 1.1 && < 1.2

library:
  source-dirs: src

internal-libraries:
  exalog-fixtures:
    source-dirs: fixtures
    dependencies:
    - QuickCheck >= 2.13 && < 2.14
    - exalog-engine

tests:
  exalog-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.7 && < 2.8
    - QuickCheck >= 2.13 && < 2.14
    - exalog-engine
    - exalog-fixtures
    build-tools:
    - hspec-discover >= 2.7 && < 2.8
